"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axios from "axios";
import { toast } from "sonner";
import { alertService } from "@/services/alert-service";
import { useAuthStore } from "@/store/auth-store";
import type { AlertQueryParams, CreateAlertRequest, UpdateAlertRequest } from "@/types/alert-api";
const keys = { all: ["alerts"] as const, list: (p: AlertQueryParams) => ["alerts", "list", p] as const, detail: (id: number) => ["alerts", "detail", id] as const };
const error = (value: unknown, fallback: string) => axios.isAxiosError<{ message?: string }>(value) ? value.response?.data?.message ?? fallback : value instanceof Error ? value.message : fallback;
export function useAlerts(params: AlertQueryParams, enabled = true) { const token = useAuthStore((s) => s.accessToken); return useQuery({ queryKey: keys.list(params), queryFn: () => alertService.listAlerts(params), enabled: enabled && Boolean(token) }); }
export function useAlert(id: number | null) { return useQuery({ queryKey: keys.detail(id ?? 0), queryFn: () => alertService.getAlert(id ?? 0), enabled: Boolean(id) }); }
export function useCreateAlert() { const client = useQueryClient(); return useMutation({ mutationFn: (payload: CreateAlertRequest) => alertService.createAlert(payload), onSuccess: () => { toast.success("Alert created successfully."); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to create alert.")) }); }
export function useUpdateAlert() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, payload }: { id: number; payload: UpdateAlertRequest }) => alertService.updateAlert(id, payload), onSuccess: (alert) => { toast.success("Alert updated successfully."); client.setQueryData(keys.detail(alert.id), alert); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to update alert.")) }); }
export function useDeleteAlert() { const client = useQueryClient(); return useMutation({ mutationFn: (id: number) => alertService.deleteAlert(id), onSuccess: () => { toast.success("Alert deleted successfully."); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to delete alert.")) }); }
export function useAcknowledgeAlert() { const client = useQueryClient(); return useMutation({ mutationFn: (id: number) => alertService.acknowledgeAlert(id), onSuccess: (alert) => { toast.success("Alert acknowledged."); client.setQueryData(keys.detail(alert.id), alert); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to acknowledge alert.")) }); }
export function useResolveAlert() { const client = useQueryClient(); return useMutation({ mutationFn: (id: number) => alertService.resolveAlert(id), onSuccess: (alert) => { toast.success("Alert resolved."); client.setQueryData(keys.detail(alert.id), alert); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to resolve alert.")) }); }
export function useAttachAlertIncident() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, incidentId }: { id: number; incidentId: number }) => alertService.attachIncident(id, incidentId), onSuccess: (alert) => { toast.success("Incident linked to alert."); client.setQueryData(keys.detail(alert.id), alert); return client.invalidateQueries({ queryKey: keys.all }); }, onError: (value) => toast.error(error(value, "Failed to link incident.")) }); }
