"use client";
import { useEffect, useRef, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import axios from "axios";
import { Boxes, X } from "lucide-react";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { resourceFormSchema, type ResourceFormInput } from "@/lib/validation/resource";
import type { ProjectResponse } from "@/types/project-api";
import type { ResourcePayload, ResourceResponse } from "@/types/resource-api";
import { ResourceFormFields } from "./resource-form-fields";
const defaults: ResourceFormInput = { project_id: "", parent_resource_id: "", kind: "Pod", name: "", display_name: "", external_id: "", provider: "", region: "", namespace: "", cluster: "", status: "ACTIVE", health: "UNKNOWN", labelsText: "{}", annotationsText: "{}", metadataText: "{}" };
export function ResourceModal({ open, resource, projects, onClose, onSubmit, pending }: { open: boolean; resource?: ResourceResponse | null; projects: ProjectResponse[]; onClose: () => void; onSubmit: (payload: ResourcePayload) => Promise<unknown>; pending: boolean }) {
 const dialogRef = useRef<HTMLDialogElement>(null); const [submitError, setSubmitError] = useState<string | null>(null); const form = useForm<ResourceFormInput>({ resolver: zodResolver(resourceFormSchema), defaultValues: defaults });
 useEffect(() => { if (open) { form.reset(resource ? { project_id: resource.projectId, parent_resource_id: resource.parentResourceId ?? "", kind: resource.kind as ResourceFormInput["kind"], name: resource.name, display_name: resource.displayName, external_id: resource.externalId, provider: resource.provider, region: resource.region, namespace: resource.namespace, cluster: resource.cluster, status: resource.status as ResourceFormInput["status"], health: resource.health as ResourceFormInput["health"], labelsText: JSON.stringify(resource.labels ?? {}, null, 2), annotationsText: JSON.stringify(resource.annotations ?? {}, null, 2), metadataText: JSON.stringify(resource.metadata ?? {}, null, 2) } : defaults); setSubmitError(null); if (!dialogRef.current?.open) dialogRef.current?.showModal(); } else if (dialogRef.current?.open) dialogRef.current.close(); }, [open, resource, form]);
 const close = () => { if (!pending) onClose(); };
 const submit = async (input: ResourceFormInput) => { setSubmitError(null); const parsed = [input.labelsText, input.annotationsText, input.metadataText].map(parseJson); if (parsed.some((value) => value === null)) { form.setError("metadataText", { message: "Labels, annotations, and metadata must be valid JSON objects." }); return; } try { await onSubmit({ project_id: input.project_id, parent_resource_id: input.parent_resource_id || undefined, kind: input.kind, name: input.name, display_name: input.display_name, external_id: input.external_id, provider: input.provider, region: input.region, namespace: input.namespace, cluster: input.cluster, status: input.status, health: input.health, labels: parsed[0]!, annotations: parsed[1]!, metadata: parsed[2]! }); onClose(); } catch (error) { setSubmitError(axios.isAxiosError<{ message?: string }>(error) ? error.response?.data?.message ?? "Unable to save resource." : "Unable to save resource."); } };
 const editing = Boolean(resource); return <dialog ref={dialogRef} onClose={onClose} aria-labelledby="resource-modal-title" className="m-auto w-[calc(100%-2rem)] max-w-2xl rounded-3xl border p-0 text-[var(--foreground)] shadow-[var(--shadow-lg)] backdrop:bg-[var(--background)]" style={{ backgroundColor: "var(--card)", borderColor: "var(--border)" }}><form onSubmit={form.handleSubmit(submit)}><header className="flex items-start justify-between border-b p-5" style={{ borderColor: "var(--border)" }}><div className="flex items-center gap-3"><span className="rounded-2xl p-3" style={{ color: "var(--primary)", backgroundColor: "color-mix(in srgb, var(--primary) 12%, transparent)" }}><Boxes className="h-5 w-5" /></span><div><h2 id="resource-modal-title" className="text-lg font-semibold">{editing ? "Edit resource" : "Create resource"}</h2><p className="mt-1 text-sm" style={{ color: "var(--muted-foreground)" }}>{editing ? "Update this resource's recorded attributes." : "Add an infrastructure resource to a project."}</p></div></div><Button type="button" variant="ghost" onClick={close} disabled={pending} className="h-9 w-9 p-0" aria-label="Close resource dialog"><X className="h-4 w-4" /></Button></header><div className="max-h-[65vh] space-y-5 overflow-y-auto p-5"><ResourceFormFields register={form.register} errors={form.formState.errors} projects={projects} disabled={pending} />{submitError ? <p role="alert" className="text-sm" style={{ color: "var(--danger)" }}>{submitError}</p> : null}</div><footer className="flex justify-end gap-3 border-t p-5" style={{ borderColor: "var(--border)" }}><Button type="button" variant="secondary" onClick={close} disabled={pending}>Cancel</Button><Button type="submit" loading={pending}>{editing ? "Save changes" : "Create"}</Button></footer></form></dialog>;
}
function parseJson(value: string): Record<string, unknown> | null { try { const parsed: unknown = JSON.parse(value || "{}"); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null; } catch { return null; } }
