import type { Project } from "./types";

export const projects: Project[] = [
  { id: "platform-core", name: "Platform Core", description: "Shared control plane and tenant orchestration services.", health: "healthy", environment: "production", owner: { name: "Maya Chen", initials: "MC" }, members: [{ name: "Maya Chen", initials: "MC" }, { name: "Arun Patel", initials: "AP" }, { name: "Noah Williams", initials: "NW" }], services: 14, lastDeployment: "18 min ago", updatedAt: "2026-07-28T07:32:00Z", deployments: 38, icon: "layers" },
  { id: "identity-gateway", name: "Identity Gateway", description: "Authentication, authorization, and policy enforcement.", health: "healthy", environment: "production", owner: { name: "Arun Patel", initials: "AP" }, members: [{ name: "Arun Patel", initials: "AP" }, { name: "Lina Shah", initials: "LS" }], services: 8, lastDeployment: "2 hours ago", updatedAt: "2026-07-28T05:48:00Z", deployments: 24, icon: "shield-check" },
  { id: "data-pipeline", name: "Data Pipeline", description: "Event ingestion, transformation, and warehouse delivery.", health: "warning", environment: "production", owner: { name: "Noah Williams", initials: "NW" }, members: [{ name: "Noah Williams", initials: "NW" }, { name: "Iris Kim", initials: "IK" }, { name: "Maya Chen", initials: "MC" }], services: 11, lastDeployment: "4 hours ago", updatedAt: "2026-07-28T03:09:00Z", deployments: 16, icon: "database" },
  { id: "edge-network", name: "Edge Network", description: "Global traffic routing and regional edge configuration.", health: "healthy", environment: "production", owner: { name: "Lina Shah", initials: "LS" }, members: [{ name: "Lina Shah", initials: "LS" }, { name: "Arun Patel", initials: "AP" }], services: 6, lastDeployment: "Yesterday", updatedAt: "2026-07-27T17:20:00Z", deployments: 12, icon: "network" },
  { id: "developer-portal", name: "Developer Portal", description: "Internal service catalog and developer self-service workflows.", health: "healthy", environment: "staging", owner: { name: "Iris Kim", initials: "IK" }, members: [{ name: "Iris Kim", initials: "IK" }, { name: "Noah Williams", initials: "NW" }], services: 5, lastDeployment: "Yesterday", updatedAt: "2026-07-27T12:14:00Z", deployments: 9, icon: "globe" },
  { id: "billing-engine", name: "Billing Engine", description: "Usage aggregation, invoicing, and revenue reconciliation.", health: "critical", environment: "staging", owner: { name: "Maya Chen", initials: "MC" }, members: [{ name: "Maya Chen", initials: "MC" }, { name: "Lina Shah", initials: "LS" }], services: 7, lastDeployment: "3 days ago", updatedAt: "2026-07-25T08:00:00Z", deployments: 7, icon: "cpu" },
  { id: "observability", name: "Observability", description: "Metrics, logs, traces, and service-level objective tracking.", health: "healthy", environment: "development", owner: { name: "Noah Williams", initials: "NW" }, members: [{ name: "Noah Williams", initials: "NW" }, { name: "Iris Kim", initials: "IK" }, { name: "Arun Patel", initials: "AP" }], services: 9, lastDeployment: "4 days ago", updatedAt: "2026-07-24T11:30:00Z", deployments: 5, icon: "cloud-cog" },
  { id: "workflow-automation", name: "Workflow Automation", description: "Operational runbooks and automated remediation workflows.", health: "warning", environment: "development", owner: { name: "Iris Kim", initials: "IK" }, members: [{ name: "Iris Kim", initials: "IK" }, { name: "Maya Chen", initials: "MC" }], services: 4, lastDeployment: "5 days ago", updatedAt: "2026-07-23T09:40:00Z", deployments: 6, icon: "boxes" },
];
