export const ALERT_SEVERITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"] as const;
export const ALERT_STATUSES = ["OPEN", "ACKNOWLEDGED", "INVESTIGATING", "RESOLVED"] as const;
export const ALERT_SOURCES = ["MANUAL", "AI", "KUBERNETES", "PROMETHEUS", "GRAFANA", "AZURE", "DOCKER", "VM"] as const;
export const ALERT_RESOURCE_TYPES = ["POD", "DEPLOYMENT", "NODE", "SERVICE", "CONTAINER", "DATABASE", "VM", "APPLICATION", "NAMESPACE"] as const;
