"use client";
import { X } from "lucide-react";
import { ErrorState } from "@/components/common";
import { Button } from "@/components/ui/button";
import { useMetricAggregation, useMetricHistory } from "@/hooks/use-metrics";
import type { Metric } from "./types";
import { format } from "./metrics-card";
export function MetricDetailsDrawer({ metric, onClose }: { metric: Metric | null; onClose: () => void }) { const end = new Date().toISOString(); const start = new Date(Date.now() - 24 * 3600_000).toISOString(); const history = useMetricHistory(metric ? { projectId: metric.projectId, clusterId: metric.clusterId, resourceId: metric.resourceId, metricType: metric.metricType, metricName: metric.metricName, start, end, limit: 100 } : null); const aggregate = useMetricAggregation(metric ? { projectId: metric.projectId, metricType: metric.metricType, metricName: metric.metricName, start, end, interval: "hour" } : null); if (!metric) return null; return <div className="fixed inset-0 z-50 bg-black/45" onMouseDown={onClose}><aside role="dialog" aria-modal="true" aria-label="Metric details" onMouseDown={(e) => e.stopPropagation()} className="ml-auto flex h-full w-full max-w-xl flex-col border-l" style={{ backgroundColor: "var(--card)", borderColor: "var(--border)" }}><header className="flex justify-between border-b p-5" style={{ borderColor: "var(--border)" }}><div><p className="text-sm" style={{ color: "var(--muted-foreground)" }}>Metric details</p><h2 className="mt-1 text-xl font-semibold">{metric.metricName}</h2></div><Button variant="ghost" className="h-9 w-9 p-0" onClick={onClose}><X className="h-4 w-4" /></Button></header><div className="flex-1 space-y-6 overflow-y-auto p-5"><Details title="General" items={[["Metric type", metric.metricType], ["Resource", `${metric.resourceKind}: ${metric.resourceId}`], ["Cluster ID", metric.clusterId], ["Project ID", metric.projectId], ["Current value", `${format(metric.value)} ${metric.unit}`], ["Timestamp", new Date(metric.timestamp).toLocaleString()]]} />{aggregate.isError ? <ErrorState description="Unable to load aggregate values." onRetry={() => void aggregate.refetch()} /> : aggregate.data ? <Details title="Aggregated metrics (last 24 hours)" items={[["Average", `${format(aggregate.data.average)} ${aggregate.data.unit}`], ["Minimum", `${format(aggregate.data.minimum)} ${aggregate.data.unit}`], ["Maximum", `${format(aggregate.data.maximum)} ${aggregate.data.unit}`], ["Count", String(aggregate.data.count)], ["Sum", `${format(aggregate.data.sum)} ${aggregate.data.unit}`]]} /> : <p className="text-sm" style={{ color: "var(--muted-foreground)" }}>Loading aggregate values…</p>}<section><h3 className="text-sm font-semibold">History (last 24 hours)</h3>{history.isError ? <p className="mt-2 text-sm" style={{ color: "var(--danger)" }}>Unable to load metric history.</p> : <ol className="mt-3 space-y-2">{(history.data ?? []).slice(0, 12).map((point) => <li key={point.id} className="flex justify-between rounded-xl border px-3 py-2 text-sm" style={{ borderColor: "var(--border)" }}><span>{new Date(point.timestamp).toLocaleString()}</span><strong>{format(point.value)} {point.unit}</strong></li>)}</ol>}</section><Json title="Labels" value={metric.labels} /><Json title="Metadata" value={metric.metadata} /></div></aside></div>; }
function Details({ title, items }: { title: string; items: [string, string][] }) { return <section><h3 className="text-sm font-semibold">{title}</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2">{items.map(([k, v]) => <div key={k}><dt className="text-xs" style={{ color: "var(--muted-foreground)" }}>{k}</dt><dd className="mt-1 break-words text-sm">{v}</dd></div>)}</dl></section>; } function Json({ title, value }: { title: string; value: Record<string, unknown> }) { return <section><h3 className="text-sm font-semibold">{title}</h3><pre className="mt-3 overflow-x-auto rounded-xl border p-3 text-xs" style={{ borderColor: "var(--border)", backgroundColor: "var(--muted)" }}>{JSON.stringify(value ?? {}, null, 2)}</pre></section>; }
